version: "1.0"

services:
  app:
    build:
      dockerfile: development.Dockerfile
    volumes:
      - .:/app
    environment:
      - DB_HOSTNAME=db
      - DB_PORT=5432
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - DB_NAME=postgres
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - postgres-net

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
        - postgres-net
        
  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080 
    networks:
      - postgres-net

networks:
  postgres-net:

      