// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Admins          string
	Doctors         string
	Healthinsurance string
	Patients        string
	Users           string
}{
	Admins:          "admins",
	Doctors:         "doctors",
	Healthinsurance: "healthinsurance",
	Patients:        "patients",
	Users:           "users",
}
